version: '3.8'

services:
  # --- MOTOR DE PERSISTENCIA (Redis) ---
  redis:
    image: redis:alpine
    container_name: hyperion_cache
    restart: always
    networks:
      - hyperion_net
    # No es estrictamente necesario mapear puertos afuera si solo el backend lo usa,
    # pero lo dejamos para que puedas inspeccionarlo con Redis Insight si quieres.
    ports:
      - "6379:6379"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hyperion_backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis # El backend necesita que Redis exista antes de arrancar
    networks:
      - hyperion_net
    environment:
      - REDIS_HOST=redis # Usamos el nombre del servicio como host
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 8000))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: hyperion_dashboard
    restart: always
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hyperion_net

networks:
  hyperion_net:
    driver: bridge